pipeline {
    agent any

    parameters {
        string(
            name: 'BRANCH',
            defaultValue: 'release/4.9.4',
            description: 'Git branch to build'
        )
    }

    environment {
        ENV = "dev"
        HOST_BUILD_DIR = "/opt/builds"
        REPO_NAME = "aio-jira-tcms-backend"
        ANSIBLE_CONFIG = 'ansible/ansible.cfg'
        AWS_DEFAULT_REGION = 'ap-south-1'
    }

    options {
        timestamps()
        timeout(time: 60, unit: 'MINUTES')
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '3'))
    }

    stages {

        stage('Checkout & Build JAR') {
            steps {
                tcmsBuild(
                    repoName: env.REPO_NAME,
                    buildCommand: './mvnw -f pom.xml clean install -DskipTests -Pjar -pl !aio.jira.app:aio-tests-dc'
                )
            }
        }

        stage('Deploy Batch via Ansible') {
            steps {
                tcmsDeploy(playbook: 'deploy_batch.yml')
            }
        }
    }

    post {
        success {
            echo "✅ Deployment to ${ENV} successful!"
        }
        failure {
            echo "❌ Deployment failed for ${ENV}"
        }
        always {
            cleanWs()
        }
    }
}