[all:vars]
ansible_ssh_private_key_file=~/.ssh/tcms-dev.pem

[apache_server]
development-main ansible_host=15.207.162.228

[jenkins_server]
development-main ansible_host=15.207.162.228 

[haproxy_server]
development-main ansible_host=15.207.162.228 

[docker_servers]
development-main ansible_host=15.207.162.228 

[pulsar_server]
pulsar ansible_host=15.207.162.228

[tomcat_servers]
be-1  ansible_host=15.207.162.228 app_role=be-1 app_port=8081
be-2  ansible_host=15.207.162.228 app_role=be-2 app_port=8082
api-1  ansible_host=15.207.162.228 app_role=api-1 app_port=8083
api-2  ansible_host=15.207.162.228 app_role=api-2 app_port=8084

[batch_server]
batch  ansible_host=15.207.162.228

[database_primary]
primary ansible_host=13.127.192.232 pg_port=5432 pg_cluster=main pg_data=/var/lib/postgresql/18/main private_ip=10.0.8.122

[database_replica]
replica ansible_host=13.127.192.232 pg_port=5433 pg_cluster=replica pg_data=/var/lib/postgresql/18/replica private_ip=10.0.8.122

[pgbouncer_servers]
development-main ansible_host=15.207.162.228

[database:children]
database_primary
database_replica