FROM tomcat:9.0-jdk17

RUN rm -rf /usr/local/tomcat/webapps/* \
           /usr/local/tomcat/webapps.dist/*

COPY {{ docker_build.artifact_dest }} /tmp/app.war
RUN mv /tmp/app.war /usr/local/tomcat/webapps/aio-tcms.war

COPY setenv.sh /usr/local/tomcat/bin/setenv.sh

RUN sed -i 's/\r$//' /usr/local/tomcat/bin/setenv.sh && \
    chmod +x /usr/local/tomcat/bin/setenv.sh && \
    chmod -R 755 /usr/local/tomcat/webapps