- import_playbook: haproxy.yml
- import_playbook: docker.yml
- import_playbook: apache.yml
- import_playbook: jenkins.yml
- import_playbook: jenkins-post-install.yml
- import_playbook: pgbouncer.yml
- import_playbook: pgbouncer_ips.yml
- import_playbook: pulsar.yml