docker_image: "tomcat:10.1-jdk21"
aws_env_secret_name: "env_variables_all_environments"
war_path: "{{ build_dir }}/aio-jira-tcms-backend/cloud/target/aio-tcms-backend-cloud-1.0-SNAPSHOT.war"
jar_path: "{{ build_dir }}/aio-jira-tcms-backend/cloud/target/aio-tcms-batch.jar"


deploy_type: "war"   # war | batch

docker_build_matrix:
  war:
    image_name: "aio-tcms-backend"
    artifact_src: "{{ war_path }}"
    artifact_dest: "aio-tcms.war"
    dockerfile_template: "Dockerfile.war.j2"

  batch:
    image_name: "aio-tcms-batch"
    artifact_src: "{{ jar_path }}"
    artifact_dest: "aio-tcms-batch.jar"
    dockerfile_template: "Dockerfile.batch.j2"

docker_build_context: "/tmp/docker-build"
env_file_path: "{{ build_dir }}/{{ deploy_type }}.env"
container_name: "{{ docker_build_matrix[deploy_type].image_name }}-{{ app_role }}"


env_vars:
  AIO_TCMS_ENV: {{ tcms_env }}
  AIO_TCMS_ATTACHMENT_STORE_TYPE: {{ attachment_store_type }}
  AIO_TEST_BATCH: {{ aio_test_batch | default(omit) }}
  AIO_TCMS_DB_URL: jdbc:postgresql://host.docker.internal:6432/aio-tcms?assumeMinServerVersion=18.0&ApplicationName=AIO_TCMS_DEV_TOMCAT
  AIO_TCMS_DB_URL_READ_ONLY: jdbc:postgresql://host.docker.internal:6432/aio-tcms-read-only?assumeMinServerVersion=18.0&ApplicationName=AIO_TCMS_DEV_TOMCAT
  AIO_TCMS_TEMP_FOLDER: /aio-tcms-store/tmp
  AIO_TCMS_SMTP_MAIL_HOST: smtp.gmail.com
  AIO_TCMS_SMTP_MAIL_PORT: 587
  AIO_TCMS_ENV_ORIGIN: https://{{haproxy_domain}}
  JCMA_DATA_DIRECTORY: /aio-tcms-jcma
  PULSAR_URL: pulsar://{{ hostvars['pulsar'].ansible_default_ipv4.address }}:6650
  AIO_TCMS_JENKINS_PROXY_IP: host.docker.internal
  AIO_TCMS_ATTACHMENT_STORE_ROOT: /aio-tcms-store
